### ISSUE TITLE
please move all dynamic values to a dedicated config component

### ISSUE THREAD

**Issue by itai-gendler** [TehilaTheStudent/SkillCode-backend#1]
https://github.com/TehilaTheStudent/SkillCode-backend/blob/d1e29a4d189f595ea7287d6c01f31a0aa18ce1d0/cmd/main.go#L14

**Comment by TehilaTheStudent** [comment]
thank you for the feedback!

**Comment by itai-gendler** [comment]
of course.
once you have some working scenarios, even if just a few, i suggest we zoom
and go over them

**Comment by itai-gendler** [comment]
better with some working ui and backend. even if it's only partial
